### PR TITLE
Rename `convert` to `imagemagick_convert`

### PR DESCRIPTION
**Pull request by ericphanson**
Fix the breakage introduced by `convert` conflicting with `Base.convert`.

This was accomplished by finding-and-replace all `convert` => `imagemagick_convert`, followed by `"imagemagick_convert"` => `"convert"` (with the quotes, to restore the correct paths). I tested `imagemagick_convert(f)` locally and it worked (i.e. could be used to converted a file as usual).

### CODE REVIEW

**Comment by giordano** [comment]
Thanks!

**Comment by giordano** [comment]
Could you also please bump the build number in https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/blob/d706c5d103320ef23a40f7c2d03da13326cbb156/Project.toml#L3?
It should become
```toml
version = "6.9.10-12+3"
```

**Comment by ericphanson** [comment]
Sure, done :)

**Comment by giordano** [comment]
Thank you!

**Pull request merged**
